CREATE OR REPLACE STREAM "DESTINATION_SQL_STREAM" (SHARD_ID VARCHAR(64), TEM_MIN REAL, UMD_MAX INTEGER, RAD_GLO REAL, CHUVA REAL,
UMD_INS INTEGER);

CREATE OR REPLACE PUMP "STREAM_PUMP1" AS INSERT INTO "DESTINATION_SQL_STREAM"
    SELECT STREAM SHARD_ID, MIN(TEM_MIN), MAX(UMD_MAX), SUM(RAD_GLO), SUM(CHUVA), AVG(UMD_INS)
        FROM "SOURCE_SQL_STREAM_001"
        GROUP BY SHARD_ID,
            STEP("SOURCE_SQL_STREAM_001".ROWTIME BY INTERVAL '2' SECOND);
